version: '3'

services:
  music-bot:
    build: .
    container_name: music-bot
    environment:
      - BOT_TOKEN=YOUR_BOT_TOKEN
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - ffmpeg
    networks:
      - bot-network

  ffmpeg:
    image: jrottenberg/ffmpeg:4.3-alpine
    container_name: ffmpeg
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge